linea1 = [
    "Observatorio",
    "Tacubaya",
    "Juanacatlán",
    "Chapultepec",
    "Sevilla",
    "Insurgentes",
    "Cuauhtémoc",
    "Balderas",
    "Salto del Agua",
    "Isabel la Católica",
    "Pino Suárez",
    "Merced",
    "Candelaria",
    "San Lázaro",
    "Moctezuma",
    "Balbuena",
    "Boulevard Puerto Aéreo",
    "Gómez Farías",
    "Zaragoza",
    "Pantitlán",
]

linea2 = [
    "Cuatro Caminos",
    "Panteones",
    "Tacuba",
    "Cuitláhuac",
    "Popotla",
    "Colegio Militar",
    "Normal",
    "San Cosme",
    "Revolución",
    "Hidalgo",
    "Bellas Artes",
    "Allende",
    "Zócalo",
    "Pino Suárez",
    "San Antonio Abad",
    "Chabacano",
    "Viaducto",
    "Xola",
    "Villa de Cortés",
    "Nativitas",
    "Portales",
    "Ermita",
    "General Anaya",
    "Tasqueña",
]

linea3 = [
    "Indios Verdes",
    "Deportivo 18 de Marzo",
    "Potrero",
    "La Raza",
    "Tlatelolco",
    "Guerrero",
    "Hidalgo",
    "Juárez",
    "Balderas",
    "Niños Héroes",
    "Hospital General",
    "Centro Médico",
    "Etiopía/Plaza de la Transparencia",
    "Eugenia",
    "División del Norte",
    "Zapata",
    "Coyoacán",
    "Viveros/Derechos Humanos",
    "Miguel Ángel de Quevedo",
    "Copilco",
    "Universidad",
]

linea4 = [
    "Martín Carrera",
    "Talismán",
    "Bondojito",
    "Consulado",
    "Canal del Norte",
    "Morelos",
    "Candelaria",
    "Fray Servando",
    "Jamaica",
    "Santa Anita",
]

linea5 = [
    "Politécnico",
    "Instituto del Petróleo",
    "Autobuses del Norte",
    "La Raza",
    "Misterios",
    "Valle Gómez",
    "Consulado",
    "Eduardo Molina",
    "Aragón",
    "Oceanía",
    "Terminal Aérea",
    "Hangares",
    "Pantitlán",
]

linea6 = [
    "El Rosario",
    "Tezozómoc",
    "Azcapotzalco",
    "Ferrería/Arena Ciudad de México",
    "Norte 45",
    "Vallejo",
    "Instituto del Petróleo",
    "Lindavista",
    "Deportivo 18 de Marzo",
    "La Villa-Basílica",
    "Martín Carrera",
]

linea7 = [
    "El Rosario",
    "Aquiles Serdán",
    "Camarones",
    "Refinería",
    "Tacuba",
    "San Joaquín",
    "Polanco",
    "Auditorio",
    "Constituyentes",
    "Tacubaya",
    "San Pedro de los Pinos",
    "San Antonio",
    "Mixcoac",
    "Barranca del Muerto",
]

linea8 = [
    "Garibaldi / Lagunilla",
    "Bellas Artes",
    "San Juan de Letrán",
    "Salto del Agua",
    "Doctores",
    "Obrera",
    "Chabacano",
    "La Viga",
    "Santa Anita",
    "Coyuya",
    "Iztacalco",
    "Apatlaco",
    "Aculco",
    "Escuadrón 201",
    "Atlalilco",
    "Iztapalapa",
    "Cerro de la Estrella",
    "UAM-I",
    "Constitución de 1917",
]

linea9 = [
    "Tacubaya",
    "Patriotismo",
    "Chilpancingo",
    "Centro Médico",
    "Lázaro Cárdenas",
    "Chabacano",
    "Jamaica",
    "Mixiuhca",
    "Velódromo",
    "Ciudad Deportiva",
    "Puebla",
    "Pantitlán",
]

lineaA = [
    "Pantitlán",
    "Agrícola Oriental",
    "Canal de San Juan",
    "Tepalcates",
    "Guelatao",
    "Peñón Viejo",
    "Acatitla",
    "Santa Marta",
    "Los Reyes",
    "La Paz",
]

lineaB = [
    "Ciudad Azteca",
    "Plaza Aragón",
    "Olímpica",
    "Ecatepec",
    "Múzquiz",
    "Río de los Remedios",
    "Impulsora",
    "Nezahualcóyotl",
    "Villa de Aragón",
    "Bosque de Aragón",
    "Deportivo Oceanía",
    "Romero Rubio",
    "Ricardo Flores Magón",
    "San Lázaro",
    "Morelos",
    "Tepito",
    "Lagunilla",
    "Garibaldi",
    "Guerrero",
    "Buenavista",
]

linea12 = [
    "Mixcoac",
    "Insurgentes Sur",
    "20 de Noviembre",
    "Zapata",
    "Parque de los Venados",
    "Eje Central",
    "Ermita",
    "Mexicaltzingo",
    "Atlalilco",
    "Culhuacán",
    "San Andrés Tomatlán",
    "Lomas Estrella",
    "Calle 11",
    "Periférico Oriente",
    "Tezonco",
    "Olivos",
    "Nopalera",
    "Zapotitlán",
    "Tlaltenco",
    "Tláhuac",
]

lineas = [
    linea1,
    linea2,
    linea3,
    linea4,
    linea5,
    linea6,
    linea7,
    linea8,
    linea9,
    lineaA,
    lineaB,
    linea12
]
